const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const projectRoot = path.resolve(__dirname, "..");
const horseRoot = path.join(projectRoot, "js", "data", "historical-horses");
const horseIndexFile = path.join(horseRoot, "index.js");
const defaultOutputRoot = path.join(projectRoot, "dist");

function normalizeWebPath(file) {
  return file.replaceAll("\\", "/");
}

function listFiles(directory) {
  return fs.readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const file = path.join(directory, entry.name);
      return entry.isDirectory() ? listFiles(file) : [file];
    })
    .sort((left, right) => left.localeCompare(right));
}

function copyDirectory(source, destination) {
  fs.mkdirSync(destination, { recursive: true });
  fs.readdirSync(source, { withFileTypes: true }).forEach((entry) => {
    const sourceFile = path.join(source, entry.name);
    const destinationFile = path.join(destination, entry.name);
    if (entry.isDirectory()) {
      copyDirectory(sourceFile, destinationFile);
      return;
    }
    if (entry.isFile()) fs.copyFileSync(sourceFile, destinationFile);
  });
}

function readHorseManifest() {
  const source = fs.readFileSync(horseIndexFile, "utf8");
  const manifestBlock = source.match(/const files = \[([\s\S]*?)\n\s*\];/);
  if (!manifestBlock) {
    throw new Error("Unable to find the historical-horse files manifest.");
  }

  const files = Array.from(
    manifestBlock[1].matchAll(/^\s*"([^"]+\.js)",?\s*$/gm),
    (match) => match[1]
  );
  if (files.length === 0) {
    throw new Error("The historical-horse files manifest is empty.");
  }

  const duplicateFiles = files.filter((file, index) => files.indexOf(file) !== index);
  if (duplicateFiles.length > 0) {
    throw new Error(`Historical-horse files are listed more than once: ${[...new Set(duplicateFiles)].join(", ")}`);
  }

  files.forEach((file) => {
    const normalized = path.posix.normalize(file);
    if (
      normalized !== file
      || path.posix.isAbsolute(file)
      || normalized === ".."
      || normalized.startsWith("../")
    ) {
      throw new Error(`Historical-horse manifest contains an unsafe path: ${file}`);
    }
  });

  const dataFiles = listFiles(horseRoot)
    .filter((file) => file.endsWith(".js"))
    .filter((file) => !["index.js", "registry.js"].includes(path.basename(file)))
    .map((file) => normalizeWebPath(path.relative(horseRoot, file)));
  const manifestSet = new Set(files);
  const dataFileSet = new Set(dataFiles);
  const missingFiles = files.filter((file) => !dataFileSet.has(file));
  const unlistedFiles = dataFiles.filter((file) => !manifestSet.has(file));

  if (missingFiles.length > 0) {
    throw new Error(`Historical-horse manifest files do not exist: ${missingFiles.join(", ")}`);
  }
  if (unlistedFiles.length > 0) {
    throw new Error(`Historical-horse data files are not listed in the manifest: ${unlistedFiles.join(", ")}`);
  }

  return files;
}

function createHorseBundle(files) {
  const sections = files.map((file) => {
    const source = fs.readFileSync(path.join(horseRoot, ...file.split("/")), "utf8");
    return `// Source: ${file}\n${source.trimEnd()}`;
  });
  return `// Generated by scripts/build-web.js. Do not edit.\n${sections.join("\n\n")}\n`;
}

function createProductionLoader(files, bundlePath) {
  return `// Generated by scripts/build-web.js. Do not edit.
(function () {
  const ns = (window.Keiba = window.Keiba || {});
  const files = ${JSON.stringify(files, null, 2)};
  const bundleFile = ${JSON.stringify(bundlePath)};

  function loadScript(file) {
    return new Promise((resolve, reject) => {
      const script = document.createElement("script");
      script.src = file;
      script.onload = () => resolve(file);
      script.onerror = () => reject(new Error(\`Failed to load \${file}\`));
      document.head.appendChild(script);
    });
  }

  ns.HistoricalHorseFiles = files.slice();
  ns.HistoricalHorseLoadReport = null;
  ns.HistoricalHorsesReady = Promise.allSettled([loadScript(bundleFile)])
    .then((results) => {
      const bundleFailed = results[0].status === "rejected";
      const failedFiles = bundleFailed ? files.slice() : [];
      ns.HistoricalHorseLoadReport = {
        total: files.length,
        loaded: bundleFailed ? 0 : files.length,
        failed: failedFiles.length,
        failedFiles
      };
      if (bundleFailed) {
        console.error("Historical horse bundle failed to load:", bundleFile);
      }
      ns.HistoricalHorses = ns.HistoricalHorseRegistry.all();
      return ns.HistoricalHorses;
    });
})();
`;
}

function assertSafeOutputRoot(outputRoot) {
  const resolved = path.resolve(outputRoot);
  const parsedRoot = path.parse(resolved).root;
  if (resolved === parsedRoot || resolved === projectRoot || resolved === path.dirname(projectRoot)) {
    throw new Error(`Refusing to replace unsafe build output directory: ${resolved}`);
  }
  return resolved;
}

function buildWeb(options = {}) {
  const outputRoot = assertSafeOutputRoot(options.outputRoot || defaultOutputRoot);
  const files = readHorseManifest();
  const bundle = createHorseBundle(files);
  const hash = crypto.createHash("sha256").update(bundle).digest("hex").slice(0, 12);
  const bundleName = `historical-horses.${hash}.js`;
  const bundlePath = `assets/${bundleName}`;

  fs.rmSync(outputRoot, { recursive: true, force: true });
  fs.mkdirSync(outputRoot, { recursive: true });
  fs.copyFileSync(path.join(projectRoot, "index.html"), path.join(outputRoot, "index.html"));
  copyDirectory(path.join(projectRoot, "css"), path.join(outputRoot, "css"));
  copyDirectory(path.join(projectRoot, "js"), path.join(outputRoot, "js"));

  const assetsRoot = path.join(outputRoot, "assets");
  fs.mkdirSync(assetsRoot, { recursive: true });
  const sourceAssetsRoot = path.join(projectRoot, "assets");
  if (fs.existsSync(sourceAssetsRoot)) copyDirectory(sourceAssetsRoot, assetsRoot);
  fs.writeFileSync(path.join(assetsRoot, bundleName), bundle, "utf8");

  const productionLoader = createProductionLoader(files, bundlePath);
  const productionLoaderFile = path.join(outputRoot, "js", "data", "historical-horses", "index.js");
  fs.writeFileSync(productionLoaderFile, productionLoader, "utf8");

  const productionIndexFile = path.join(outputRoot, "index.html");
  const productionIndex = fs.readFileSync(productionIndexFile, "utf8");
  const sourceLoaderTag = '<script src="js/data/historical-horses/index.js"></script>';
  const versionedLoaderTag = `<script src="js/data/historical-horses/index.js?v=${hash}"></script>`;
  if (productionIndex.split(sourceLoaderTag).length !== 2) {
    throw new Error("Expected exactly one historical-horse loader script in index.html.");
  }
  fs.writeFileSync(productionIndexFile, productionIndex.replace(sourceLoaderTag, versionedLoaderTag), "utf8");

  return {
    outputRoot,
    files,
    hash,
    bundlePath,
    bundleFile: path.join(assetsRoot, bundleName),
    loaderFile: productionLoaderFile
  };
}

if (require.main === module) {
  const result = buildWeb();
  console.log(`Built ${result.files.length} historical-horse files into ${result.bundlePath}.`);
}

module.exports = {
  buildWeb,
  createHorseBundle,
  createProductionLoader,
  readHorseManifest
};
